import type { Metadata } from "next"

import { TemporaryPagesContextProvider } from "./contexts/TemporaryPagesContext"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TemporaryPagesContextProvider>
          <header>Header</header>

          {children}

          <footer>Footer</footer>
        </TemporaryPagesContextProvider>
      </body>
    </html>
  )
}
